TextStorage component
rparrett/bevy_simple_text_input pull request #17
Opened 2024-02-16 14:39 UTC by Leinnan

Simplifies access to the input field content, solves https://github.com/rparrett/bevy_simple_text_input/issues/5
After change, there is an option to detect text change via queries like `text: Query<&TextStorage, Changed<TextStorage>>,`

2024-02-16 14:59 UTC, rparrett commented
Thanks! This generally looks good. I might have a few tweaks when I take a closer look later.

Any chance you could do the reflect / type registrations in a separate PR? And you can leave out the changelog and `Cargo.toml` changes.

2024-02-16 16:43 UTC, Leinnan commented
@rparrett done

2024-02-16 17:04 UTC, rparrett requested changes
We need to handle users initializing their bundles with a value as well.

2024-02-16 17:04 UTC, rparrett commented on src/lib.rs
> -                        value: format!("{}{}", text.sections[0].value, text.sections[2].value),
I think this is slightly incorrect.

If e.g. `delete` and `enter` arrive on the same frame, the event will not contain the results of the `delete`.

Maybe add a local `submitted` variable and do the actual event submission after the value is updated?

2024-02-16 17:04 UTC, rparrett commented on src/lib.rs
> +    container: TextStorage,
`container` should be `storage`.

But what do you think about renaming `TextStorage` to `TextInputValue`?

2024-02-16 17:04 UTC, rparrett commented on src/lib.rs
> +/// A component for the text containing input.
```suggestion
/// A component containing the current value of the text input.
```

2024-02-17 17:33 UTC, Leinnan commented
@rparrett Based on your feedback I took a bit of different approach and reuse existing component instead of adding new one. Also reworked a bit the moment when the event is called, so now it should cover the case that you were describing.

2024-02-17 21:02 UTC, rparrett commented
Thanks! I'm going to follow up quickly with some small tweaks -- I don't have a ton of time and want to get a build out for Bevy 0.13 this afternoon.

2024-02-17 21:02 UTC, merged